version: '3'

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "33333:3306"
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s


  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code

    command: ["bash", "-c", "python manage.py makemigrations && python manage.py migrate   && python manage.py runserver 0.0.0.0:8000"]

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=book
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_PORT=3306

    depends_on:
      mysql: 
        condition: service_healthy
 